version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      # Group all npm dependencies for minor and patch updates
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'npm'
    directory: '/status-page'
    schedule:
      interval: 'weekly'
    groups:
      # Group all npm dependencies for minor and patch updates
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
